### ISSUE TITLE
Create Landing Page [ 8 hours ]

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/madrona-priorities#78]
- [x] Create physical page
- [x] style to look like current apps page (less important)
- [x] replace "learn more" header link with "Data and Methods"
- [x] create "Tool Description" header link
- [x] include new flatblocks: 
- [x] about-intro -> landing page ("Introduction" section)
- [x] data-and-methods -> data and Methods tab (both on page and header link)
- [x] sort out "help" from "Tool Description" (See Jocelyn's comment below)

**Comment by jtutak** [comment]
I think the way to do this -- if the tool can live on labs permanently -- is to leave the tool where it is, but have "Learn More" link to http://aquatic-priorities.apps.ecotrust.org/docs.html and "Get Help" link to http://aquatic-priorities.apps.ecotrust.org/tool_description.html

**Comment by rhodges** [comment]
I can not recommend leaving it on labs permanently. Labs is not a production server and is designed to allow for significant downtime. Also, my plan is to sunset it in the near future.

**Comment by jtutak** [comment]
Good to know. We'll have to come up with another plan. We may want to change this issue to something like "Migrate tool to Apps" with the landing page as a sub-task?

**Comment by jtutak** [comment]
Crap, and then this has to become high priority.

**Comment by jtutak** [comment]
Sort out "help" (on labs) from "tool description" (on apps):
- "Get Help" should be changed to "More Information"
- The text should include what is currently on http://aquatic-priorities.apps.ecotrust.org/tool_description.html (I'd copy over the text but I don't have access to flatblocks on apps)
- We can either embed the tutorial videos on this page or link to another as on apps, I have no preference.

I think that makes this shovel ready; if not, we can address it when I get back.

**Comment by rhodges** [comment]
Complete: ccfc4bb78308a885da7e33133bc7256f34d18a72
