### ISSUE TITLE
Sub-basin name in hover text needs correction

### ISSUE THREAD

**Issue by jtutak** [Ecotrust/madrona-priorities#83]
The Wilson-Trask-Nestucca sub-basin is misspelled (Wilson-Trusk-Nestuccu) when you hover over/click on it, and that carries through to the scenario outputs (watersheds tab).

Can you update that text easily? I've updated both of the shapefiles in \Terra\GIS\projects\projects2012\USFWS_Update\Analysis\Output\ to reflect that update, if reloading is the easiest way.

**Comment by jtutak** [comment]
I also updated the Planning Unit under the "Seak" section of the admin page, which fixed the sub-basin title in the Watersheds tab in the output/results, but not in the map.

**Comment by jtutak** [comment]
Actually, before you do that: Dan asked that we add another three geographies (the three states) to the prioritization process. 
1. Is that a lot of work for you?
2. If it's not, then I can update the input shapefiles and spreadsheets to make that change, and when you reload them the sub-basin in question should be updated.

**Comment by rhodges** [comment]
Both the updated geographies and the updated PU name, if put in the update files will be a simple matter to fix forever - much easier and permanent than updating by hand.
